import type { Metadata } from 'next'
import PropgressProvider from '@/providers/progress.provider'
import { inter } from '@/fonts/fonts'

import 'normalize.css'
import '@/styles/index.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <PropgressProvider>{children}</PropgressProvider>
      </body>
    </html>
  )
}
